### ISSUE TITLE
add questions/answers to Puzzle A

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#140]
Question 1: Which of these is the design used for painting the cornhole boards?
Answers: (series of images from attached Word doc)
[Puzzle A Question 1 Answers.docx](https://github.com/iamsammak/thehuntgame/files/2883121/Puzzle.A.Question.1.Answers.docx)
**Answer is second image from the left.**

Question 2: Which Valspar paint isn't used?
Answers: Ultra White, Coral Ridge, **New Peach**

Question 3: How many cornhole bags does each team play with?
Answers: 3, **4**, 5, 6

**Comment by ihurrahi** [comment]
@cschois1, could you maybe upload the pictures to Google Drive, or just upload them into this ticket? Doc doesn't seem to have any images for me.

**Comment by cschois1** [comment]
Oh sorry I forgot to respond! Let me know if these images work here.
![puzzlea4](https://user-images.githubusercontent.com/47805940/53396939-9c156b00-395a-11e9-90b5-82d5a5c82903.png)
![puzzlea3](https://user-images.githubusercontent.com/47805940/53396940-9c156b00-395a-11e9-9c7a-1c59675810d9.png)
![puzzlea2](https://user-images.githubusercontent.com/47805940/53396941-9c156b00-395a-11e9-807f-67b4a1d6bf98.png)
![puzzlea1](https://user-images.githubusercontent.com/47805940/53396942-9cae0180-395a-11e9-8630-10a6095c4ae0.png)
