### ISSUE TITLE
move Matt's base intro to the home page

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#142]

**Comment by cschois1** [comment]
It would be a nice detail if we could move this just for the intro base. The "Need a hint?" can remain on top above all other prompts that show up throughout the game on Matt's page. If this will be too much work, then no problem. It's just a minor request that I don't mind not implementing (especially if any of you think it would be better to remain as is.)

**Comment by ihurrahi** [comment]
I wonder if the intro text should be separate from Matt's page. If someone joins later and the table has already gone past stage 1, they wouldn't have any context to what's going on. what if we put the intro text on the home page where you select the table? or have a popup over the entire screen when someone joins?

**Comment by cschois1** [comment]
Hmm that's true. I like the popup idea idea so as to keep Matt's page as clean as possible. I'll rewrite the prompts for the intro and Matt's base then.

**Comment by ihurrahi** [comment]
for the popup, we probably won't be able to tell when someone refreshes vs is coming in for the first time, so people who refresh might see it too

**Comment by cschois1** [comment]
Hmm...if we keep it to the home page, is it possible to squeeze in the amount of prompt we have now and still have the headshots in one view (i.e. the player doesn't need to scroll each time at the home page)?

**Comment by ihurrahi** [comment]
Sorry, by the home page, I'm talking about the page where the table number is selected

**Comment by ihurrahi** [comment]
But yeah, I don't think the page with the headshots is going to fit everything unless it's a pop up

**Comment by cschois1** [comment]
Ah, I see. Then, yes, the home page where they select the table number is where the intro message should be. Let me re-write these prompts and then get back to you then.

**Comment by cschois1** [comment]
Rewrote prompts, highlighted in yellow on the spreadsheet:

Intro: "We really need your help! With everything going on today, the bridal party somehow lost the key to the getaway car. No one is sure who had it last, so you'll need to ask around and see if anyone can remember anything.

It doesn't matter which table finds it first--Chris and Christine would love for your table to finish this entire adventure and show them that you found the key!

Each of the bridal party members is looking for the key. If you can't figure out what they're asking for or how to help them, ask the best man and he can give you a hint (unless you want to finish without using any hints!)."

Matt's base: You find Matt with the groom's family, talking about the lost key.
