### ISSUE TITLE
hint 2h shouldn't display if puzzle 2s hasn't been reached

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#144]
I think (based on my earlier testing) that hint 2h displayed before I went to Kristi's page for the puzzle prompt. If the player hasn't started puzzle 2 by navigating to Kristi's page, then we ideally shouldn't show 2h (or anything at all if a player asks Matt for a hint).

Another related change would be to change the prompt for 2h to include something about Kristi, like "You found a riddle after visiting Kristi? Hmm...if it's not written in ink, then maybe it's white space?"

If you think that updating the 2h prompt would be clear enough for the player (such that the player doesn't think that 2h is applied to Matt's puzzle 4), then I'm okay with just updating the prompt and letting 2h display before 2s is technically "reached".

**Comment by ihurrahi** [comment]
i'm seeing that 2h does not display before visiting Kristi's page. i'm actually not seeing any hints in the live version right now, but i see them showing up correctly when testing. let's revisit this when the latest changes go live.

**Comment by ihurrahi** [comment]
will update the hint text though

**Comment by ihurrahi** [comment]
going to close for now, feel free to reopen if you see the hint still not displaying
