### ISSUE TITLE
update puzzle 6 with new maze layout

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#148]
When I play-tested the original puzzle 6 without recalling the solution, I was able to solve it within a minute. :( How long does it take to build out the maze for this puzzle? For example, I made it significantly harder (though it may just add a couple more minutes to the solve time) by expanding the maze to 12x12 and custom editing it to have longer rivers (dead-ends). If you think you can easily make an even bigger maze (even with all the other edits we have planned for this game), then I would entertain expanding this maze even farther by adding another 3 cells around to make it 15x15. However, I think I would be comfortable with the difficulty level of this new 12x12 if you guys can at least do that. Let me know what you guys think.

[Maze for Puzzle 6.xlsx](https://github.com/iamsammak/thehuntgame/files/2884007/Maze.for.Puzzle.6.xlsx)

**Comment by ihurrahi** [comment]
Keep in mind that it will take some getting used to how things work - ran it by my wife and it definitely took her a bit of time to understand what was happening.
It's not super hard to add more cells to 15x15 if you would like!

**Comment by cschois1** [comment]
I see. Do you recall about how long she took with the puzzle? If she took longer than...7 minutes by herself, then I think that should be the level of difficulty to expect (given that having more people would likely decrease solving time to under 5 minutes).

**Comment by ihurrahi** [comment]
btw @cschois1, i was able to figure out how to do multiple icons per cell, so i was able to use the original maze and you don't need to worry about corners going in two different directions for future mazes
