### ISSUE TITLE
updates for Puzzle 7

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#151]
1. Can we use switches that have a clearer on/off status similar to these? [On/Off switch](https://www.google.com/imgres?imgurl=https%3A%2F%2Fmir-s3-cdn-cf.behance.net%2Fproject_modules%2Fdisp%2F413da616058775.562a4d5aca04f.png&imgrefurl=http%3A%2F%2Fkidskunst.info%2F13%2F05771-on-switch-png.htm&docid=gPvgSEziURp8SM&tbnid=Tb5wtZSo6OtASM%3A&vet=10ahUKEwjytubt5svgAhUGHnwKHei7BFwQMwikASgWMBY..i&w=400&h=307&itg=1&bih=746&biw=1506&q=on%20off%20switch&ved=0ahUKEwjytubt5svgAhUGHnwKHei7BFwQMwikASgWMBY&iact=mrc&uact=8)

2. Can we number each switch so that the clues don't have to refer to rows/columns?

3. Depending on the design impact of these requests, we might need to rearrange the switches to be in two columns (rather than two rows) or something like that. So long as each switch is clearly numbered, I think any arrangement should suffice.

4. I can rewrite the clues and provide them to you soon, but that should only impact text and which switches are correct (i.e. the design and arrangement should be unaffected by my different clues).

**Comment by cschois1** [comment]
Ok, I've written out the clues for puzzle 7, assuming that the 10 switches are arranged in a 2 column, 5 row format, where 1-5 are on the left and 6-10 are on the right. I tested out solving this riddle a few times and I do believe it has an actual solution without having to guess anything. However, it would be awesome if one of you built out the puzzle while the other two tested it blindly so that we can make sure that the solution is actually reachable and unique (i.e. you don't have to guess).

I've updated the prompts on the Google doc with all these clues. These clues in this Word doc should display after the universal prompt of "___ recalls the instructions given to him/her."

[Puzzle 7 Key.docx](https://github.com/iamsammak/thehuntgame/files/2892736/Puzzle.7.Key.docx)

5. Also, can we update what happens when an incorrect answer is entered? I want to make sure to Sheldon-proof this puzzle so that people can't just brute force their way through. How about we disable the "submit" button (or whatever it is) for a minute after each incorrect answer, in addition to displaying a prompt like, ""You activated the panel's security, which locks you out! You need to wait a minute before trying again."

**Comment by ihurrahi** [comment]
just to clarify, Ryan has the actual puzzle, but also a set of instructions?

**Comment by cschois1** [comment]
Yes, I had written the puzzle so that Ryan's page has the puzzle and a set of instructions. Will that work? I can easily rearrange the clues if it's better for Ryan's page to be clear of instructions and only have the puzzle. Let me know what you think would be better.

**Comment by ihurrahi** [comment]
nah it's fine, just wanted to make sure
