### ISSUE TITLE
changes to Puzzle 1

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#165]
Can we change puzzle 1 so that, instead of a dynamic Caesar cipher that depends on the table number of the player, the Caesar cipher depends on the total number of tables?

The main reason for this is that I recognize quite a few people will be playing this game that was at Andy's wedding where the exact same puzzle took place. If we change the "key" to the Caesar cipher, then I think that will even the playing grounds quite a bit (especially since the easy Puzzle A tells the players that it's a Caesar cipher). Thus, even those who were at Andy's wedding would need to "figure out the key" to the cipher rather than blasting right past this puzzle.

I can reword the prompts so that the clue is hidden in Puzzle 1's prompt.

**Comment by pewpewpowpow** [comment]
and the total number of tables is 30?

**Comment by cschois1** [comment]
Not for certain, but it should be around there. Understandably, since the total number is more than 26, the Caesar cipher would then move across the entire alphabet once through (and plus some).

**Comment by pewpewpowpow** [comment]
seems like an easy change

**Comment by ihurrahi** [comment]
yup seems easy, we'll wait for the updated prompt

**Comment by cschois1** [comment]
Prompts are updated and highlighted in yellow on the spreadsheet.

Ryan's base: "Ryan is looking from table to the next."

Ryan's 1s: "Thanks so much for helping us find the key! I had it with me when I was setting up these guest tables, but I must have misplaced it when I was grabbing all these letters. It was hard to keep track of everything when I was numbering each guest table. If I could only remember what these letters meant, then maybe I could remember where I placed the keys. Do you know what these letters mean?"

Matt's 1h: "These letters don't make any sense like this. What if we move the letters along the alphabet like Ryan had moved?"

Ryan's 1e: "Ah, that's right! That's why we had these letters. I remember that I finished setting up all the tables and then gave the key to Matt. He has a personal safe that Chris gave him, so it might be in there."

**Comment by pewpewpowpow** [comment]
Reviewed commit and looks good.

**Comment by ihurrahi** [comment]
whoops, didn't update the cipher to be fixed based on the number of tables

**Comment by pewpewpowpow** [comment]
@cschois1 Is it confirmed 30 tables?

**Comment by cschois1** [comment]
No, not yet unfortunately. We have our last RSVPs due on March 23. It's looking like it won't be anything more than 30 tables, but there is a chance that it could be less.

**Comment by ihurrahi** [comment]
waiting for real number of tables in https://github.com/iamsammak/thehuntgame/issues/199
