### ISSUE TITLE
update text 7s for Ryan

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#180]
Caught a grammar issue. Can we update Ryan's text for 7s to be the following? Change is in italics.

You find Ryan at a panel with ten switches.

"The venue manager told us to open this panel in case of _an_ emergency. Given that it's almost time for their getaway and we still don't have the key, I think this is an emergency. Only thing is that the manager told each of us how to open it, but we each only have part of the code. Can you figure this out?"

1. Switches 1 and 9 should be off.
2. Kristi’s first clue is incorrect.

**Comment by ihurrahi** [comment]
sure, will update. By the way, I had showed this to someone at work, and (among other things), they had feedback that the phrase "each of us" was confusing, so I updated it to "members of the bridal party"
