### ISSUE TITLE
plan play testing

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#192]
* find time for groups to gather. which groups? doodle?
* what do we need to bring? scrabble board, number of tables, map of venue, etc?
* what are we looking for?
* how should we facilitate? completely hands off or more guidance?

**Comment by cschois1** [comment]
- I have two other church networks I could tap into and ask for volunteers.
- I will bring the diagram/details of reception setup (Puzzles A, B, 1, 3 and 8), Welcome Table image (Puzzle 2), and scrabble board (Puzzle 5).
- I think we want to see how they process through and solve the puzzles, where are the hurdles/most difficult parts where they get stuck, how they operate as a team, what they make of Matt's hints, and how long everything takes given how many hints they use.
- I think we should be as hands-off as necessary. I think we should keep a close eye on them to make sure they aren't running into any bugs, but besides that, let them work it out until they're very clearly stuck for a significant amount of time (>10 min on a puzzle?) even with Matt's hint.

Let me know what you guys think and if you want me to tap into my networks to get volunteers.

**Comment by ihurrahi** [comment]
@cschois1 we may want to playtest this outside of meetings that you might be able to make, so is it possible to get pictures of the reception setup? for example, sam can get a group at work to play, but will need to setup the context
@iamsammak will take care of scheduling and script for introducing the game
@pewpewpowpow will take care of creating a feedback form for afterwards

**Comment by pewpewpowpow** [comment]
What do you guys think of these questions for feedback:

Did you enjoy the game?
What was your overall impression of the game?
What was the hardest part of the puzzle?
What was the most enjoyable part of the game?

Was it easy to navigate through the game?
Was it clear when you solved a puzzle?
Was it clear when a new puzzle appeared?
Were the hints helpful?

Were the instructions/clues clear and easy to understand?
Was it easy to recognize what the clues were asking?

Did you feel it was easier working as a team or playing by yourself?
Did the game make you want work as a team or play individually?

**Comment by ihurrahi** [comment]
>  What was the hardest part of the puzzle?

Maybe which puzzle was the hardest and why?
>  Was it clear when a new puzzle appeared?

What about at what point was it not clear what they needed to do next?  
>  Were the hints helpful?

and which ones in particular

**Comment by cschois1** [comment]
I see. Yeah, I can send you a document with everything that they would need as clues for the puzzles.

**Comment by cschois1** [comment]
Added in necessary pdf of all riddle solutions/clue pieces.
[Wedding Decorations Setup for Game Testing.pdf](https://github.com/iamsammak/thehuntgame/files/2995479/Wedding.Decorations.Setup.for.Game.Testing.pdf)

**Comment by pewpewpowpow** [comment]
Saw Andy's messages about Saturday. Here is a quick script I drafted. Also thought of other things to provide to maybe help disguise what is actually used.

Hi Everyone,

Thanks for joining us today and for testing our game. Before we get started, there are a few things we would like to make available to you to give you some context for the game and to more closely mimic how the end users will play and experience the game.

As some of you may know, we are creating this game for a wedding where the guests will have access to the game during the reception and will have an hour to complete the game. We have some items here that will give you a better idea of what will be at the venue as well as the layout of the venue for reference. We also included some additional items that the guests will be given on the day of the wedding that may or may not be involved in the game.

Again, we thank you again for your help. We appreciate any kind of feedback about the game, the puzzles, the flow, the experience. Let us know if you were confused at some points, thought something looked weird, or thought something was really cool or fun.

Thanks again!

Things to provide:
-Layout of the venue
-props and pictures of the photobooth
-pictures of other things at the venue
-pictures of the handouts
-picture of the wedding favors
-pictures of important people?
-pictures or access to the website?
-list of names of the family in English and Chinese?
-pictures cornhole?
-pictures of the getaway car?
-pictures of the parking lot?

**Comment by ihurrahi** [comment]
@cschois1 do you think you could try and get some of those things @pewpewpowpow listed?
In the pdf, I don't see mentioned:
water pitcher, candle lamp, yellow napkins, candy bags for puzzle B
valspar paint for puzzle A

**Comment by cschois1** [comment]
I'll try to get some of the things Sheldon mentioned tomorrow.

As for the other items Andy mentioned, the water pitcher would be implied by the "foot washing" on the ceremony diagram. The other items (candle lamp, yellow napkins, candy bags) are not supposed to be on the diagrams, since those are the "unused items" that are the answer to that puzzle.

The valspar paint can be looked up on Google with their phones (which I do expect people to use). Hopefully someone will get that and not think that using Google is cheating...
