### ISSUE TITLE
suggestions for puzzle 4

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#205]
Ok, I know I shouldn't be thinking about this so late, but I'm afraid I'm going to forget. What if the strong magnet "decodes" the keypad such that the Chinese character is displayed under each image rather than disabling one of the keys? Do you think that would be easier because then the character for the steaming pot would be clearer? From the play testing, it sounds like disabling the tree wasn't enough to make sense of the steaming pot.

The intent was that everyone there would know that I speak Cantonese instead of Mandarin (and, if not, they could easily ask around or just listen to the relatives around them). Hopefully that would lead people to ask a Cantonese speaker to solve the puzzle for them (although, they technically could Google and use a pronunciation tool like I referred to in a previous issue number). Let me know what you guys think.

**Comment by ihurrahi** [comment]
this sounds good! we'll also update the hint to include a link to a translator that should be used.

**Comment by ihurrahi** [comment]
lower priority: check and see if it's possible to make the chinese characters copy/pastable

**Comment by cschois1** [comment]
When the strong magnet is acquired, we will no longer disable one of the keys. Instead, we'll entirely replace the pictures of the keypad with the Chinese characters. They would be the following:

1. Water droplet: 水
2. Dog: 狗
3. Bok choy: 菜
4. Steaming pot: 熟
5. Fire: 火
6. Tree: 樹
7. Fish: 魚
8. Orange: 橙
9. Green onion: 蔥
0. Flower: 花

**Comment by cschois1** [comment]
Update Matt's hint for puzzle 4 to be the following:

"My Chinese name? Chris keeps on mispronouncing it! He should use an online dictionary like this one to figure out how to pronounce words."

https://www.cantoneseclass101.com/cantonese-dictionary/

**Comment by ihurrahi** [comment]
Need to also update the text around what Matt says when you have the magnet, maybe something like:
Ah, you found my magnet. It's supposed to help us unlock this safe. Let's see...yup--it looks like the magnet translated the pictures.

**Comment by cschois1** [comment]
Oh, good catch! Let's update that text to be the following:

"Ah, you found my magnet. It's supposed to help us unlock this safe. Let's see...looks like it converts the pictures into Chinese characters. Interesting..."
