### ISSUE TITLE
change answer to puzzle 3 to be a real word

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#206]

**Comment by cschois1** [comment]
We'll use a specific letter from each ingredient as the answer. The key is below:

1.	Assa**m** Black Tea (5)
2.	Tieguan**y**ing Oolong Tea (8)
3.	Gu**n**powder Green Tea (3)
4.	Peac**h** (5)
5.	Strawb**e**rry (7)
6.	Mang**o** (5)
7.	Jasmi**n**e (6)
8.	**O**smanthus (1)
9.	R**o**se (2)

For play testing, let's rewrite the puzzle clues to include two rows of numbers. The first is numbers 1-9, in order from left to right. The second row will have the numbers above, in order (i.e. "583575612"). For production, we'll switch the first row of numbers for symbols, just in case the tea ingredient labels get swapped around.

**Comment by cschois1** [comment]
Change the answer for puzzle 3 to be case insensitive, "honeymoon".

**Comment by cschois1** [comment]
Update puzzle 3's hint to be the following:

"Erica's clue has nine numbers. Aren't there nine ingredients at the tea table? What if you take a letter from each ingredient?"

**Comment by cschois1** [comment]
Update Erica's base text to be the following:

Erica seems concerned around the tea favor table.

"Let me think...I was setting up these bowls and then filling them with tea. What did I do next?"

**Comment by cschois1** [comment]
Update Erica's puzzle start text to be the following:

"I found this paper with these numbers on it when I was unpacking the tea. Maybe if I can make sense of these numbers, I can remember what I did next. I might have misplaced the key somewhere here."

**Comment by cschois1** [comment]
Update Erica's puzzle end text to be the following:

"Ah, I guess they're looking forward to their honeymoon as much as they are looking forward to starting a tea favor business! Everything's in order here now, but it doesn't look like the key is here."
