### ISSUE TITLE
change puzzle 1 answer

### ISSUE THREAD

**Issue by cschois1** [iamsammak/thehuntgame#215]
Some ideas:

1. nokeyhere
2. reception

**Comment by ihurrahi** [comment]
will wait for play testing results and see if the current answer is too easy

**Comment by pewpewpowpow** [comment]
Did we want to change this?

**Comment by cschois1** [comment]
I think it is fine as is. None of the playtest groups brute forced it (they just got lucky and guessed the key). I'll have to purposefully avoid seating us young folks at the tables with numbers close to 22 and 4 to help prevent this from happening during the actual game.
