### ISSUE TITLE
update puzzle B answer text to not guide user towards Matt

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#234]
if they solve puzzle B before puzzle 3 (likely scenario i think), the answer text guides them towards Matt's page.

**Comment by cschois1** [comment]
Sure, let's just remove the last line that refers to Matt:

Helena's puzzle B end:
"Thanks so much for bringing those to the car! Hm? You found a strong magnet in the trunk? Can you hold onto it for now?"

You found a strong magnet.
