### ISSUE TITLE
sync was off at some point

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#43]
chris solved puzzle 2 but none of us saw it as unlocked

**Comment by pewpewpowpow** [comment]
Can't seem to recreate the issue. Do you remember what led up to this issue?

**Comment by ihurrahi** [comment]
can't seem to reproduce easily either. i wonder if it was related to that refresh bug? we can probably leave this open and move on but we should keep our eyes peeled for this issue

**Comment by ihurrahi** [comment]
haven't seen this happen in awhile, hopefully no longer an issue
