### ISSUE TITLE
create QR code + URL printouts

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#76]

**Comment by cschois1** [comment]
Can we please update the URL to be christinechris.thinkingalaud.com? We're fine with using a subdomain under yours, but Christine doesn't like that it's just "chrischris" haha.

**Comment by ihurrahi** [comment]
haha yea it was meant to force you to find a new name :)

**Comment by ihurrahi** [comment]
already in the works, will be printed on the back of the table numbers
