### ISSUE TITLE
create answers sheet

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#77]

**Comment by ihurrahi** [comment]
@pewpewpowpow make sure chris wasn't already planning on doing this

**Comment by ihurrahi** [comment]
host it at /answers, dont show up until activated on the admin page

**Comment by cschois1** [comment]
Alright, here's the answer sheet. I have the word doc and pdf attached for you. Please review it and make sure I have all the details right. Let me know if you need me to make any changes!

[Game Answers.docx](https://github.com/iamsammak/thehuntgame/files/3107038/Game.Answers.docx)
[Game Answers.pdf](https://github.com/iamsammak/thehuntgame/files/3107039/Game.Answers.pdf)

**Comment by ihurrahi** [comment]
This looks great! Thanks for sending it over.
Have a few suggestions (if you approve them, I can just make these edits, no need to send another draft):
* mention the person each puzzle corresponded to
* translate -> shift for puzzle 1
* provide a picture for puzzle 2

**Comment by cschois1** [comment]
Good suggestions. Take a look at these now.

[Game Answers.docx](https://github.com/iamsammak/thehuntgame/files/3111111/Game.Answers.docx)
[Game Answers.pdf](https://github.com/iamsammak/thehuntgame/files/3111112/Game.Answers.pdf)
