### ISSUE TITLE
what's the deal with the # in the URL?

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#89]

**Comment by pewpewpowpow** [comment]
From what I could google, people suggest using <BrowserHistory> vs. <HashRouter>. Also found this reddit link about the "#". Does that explain the "#"?

https://www.reddit.com/r/reactjs/comments/4g2xon/react_router_how_to_get_rid_of_in_url_can_someone/

**Comment by ihurrahi** [comment]
Using what?

Yeah that link makes sense, we'll probably have to do a bit of server/nginx config changes to make this work

**Comment by pewpewpowpow** [comment]
ooo looks like it got hidden because of the carrot stuff around it.
