### ISSUE TITLE
add pictures for scrabble board (puzzle 5)

### ISSUE THREAD

**Issue by ihurrahi** [iamsammak/thehuntgame#95]

**Comment by ihurrahi** [comment]
@cschois1

**Comment by cschois1** [comment]
Here are the images for Puzzle 5. Doesn't really matter what order you go in for placing these images for the clues.

![puzzle5a](https://user-images.githubusercontent.com/47805940/53691938-829a6780-3d3c-11e9-93fd-3ce37bc4b38c.png)
![puzzle5b](https://user-images.githubusercontent.com/47805940/53691939-89c17580-3d3c-11e9-9224-b5346658916f.png)
![puzzle5c](https://user-images.githubusercontent.com/47805940/53691940-8cbc6600-3d3c-11e9-85b6-4bab697a76d0.png)
![puzzle5d](https://user-images.githubusercontent.com/47805940/53691941-8e862980-3d3c-11e9-860a-342be9c790b5.png)
![puzzle5e](https://user-images.githubusercontent.com/47805940/53691942-904fed00-3d3c-11e9-9d67-4fb8c66d711c.png)
![puzzle5f](https://user-images.githubusercontent.com/47805940/53691944-92b24700-3d3c-11e9-8d54-82559257c5a3.png)
![puzzle5g](https://user-images.githubusercontent.com/47805940/53691946-947c0a80-3d3c-11e9-9db9-06c47baf8a09.png)
![puzzle5h](https://user-images.githubusercontent.com/47805940/53691947-9645ce00-3d3c-11e9-81b0-4c2fad5c4a75.png)
